<script>
var App = window.App || {};
App.messages = {
"CSIAH0303E": "Incorrect IBMid or password. Please try again!",
"Continue": "Continue",
"CreateAccount": "Create an IBMid",
"DontHaveAccount": "Don't have an account?",
"Error.EnterDomainOrEmail": "Enter Email",
"Error.IbmidRequired": "Email or IBMid is required",
"Error.PasswordRequired": "Password required",
"Error.UsernamePasswordRequired": "IBMid and password required",
"Error.invalidCredential": "Incorrect IBMid or password. Please try again!",
"Error.invalidFederatedId": "Sorry, we currently do not support SSO with this domain or your particular IBMid is not set up with SSO for this domain.  Please {LOGIN_LINK}",
"Error.unknown": "Error {errorCode}: We are unable to process your request. Please try again later or contact the <a class='urxHelpDesk'  rel='noopener noreferrer' target='_blank' href='https://www.ibm.com/account/profile/{cc}?page=reghelpdesk'>Contact the IBMid help desk</a>",
"Login.loginAs": "Logging in as {email}",
"Login.notYou": "Not you?",
"LoginWithSSO": "Log in with your company credentials (SSO)",
"Signin": "Log in",
"companySSO": "company credential (SSO)",
"contact": "Contact",
"forgotIBMid": "Forgot IBMid?",
"forgotIdOrNeedHelp": "Forgot your IBM ID or Need help?",
"forgotPassword": "Forgot password?",
"helpdesk": "Contact the IBMid help desk",
"link.accessibility": "Accessibility",
"link.contact": "Contact",
"link.cookiePref": "Cookie preferences",
"link.privacy": "Privacy",
"link.terms": "Terms of use",
"login.heading": "Log in to IBM",
"loginWithPassword": "Login with your IBMid password",
"needHelp": "Need help?",
"or": "or",
"password.Hide": "Hide",
"password.Show": "Show",
"password.label": "Password",
"remember.label": "Remember me",
"spinner.wait": "Please wait",
"tooltip.rememberme": "You can opt to have your IBMid remembered the next time you access our website by checking the \"Remember Me\" box. If you do not wish to have your IBMid remembered the next time you access our website, leave the \"Remember Me\" box unchecked.",
"username.label": "IBMid",
"expired.heading":"Password expired",
"password.expired": "Your password has expired. Please follow this <a href=\"{{R_P_L}}\">link</a> to change it."
};
</script>